// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArtists = `-- name: CountArtists :one
SELECT count(*) FROM artists
WHERE ($1::text IS NULL OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountArtists(ctx context.Context, query *string) (int64, error) {
	row := q.db.QueryRow(ctx, countArtists, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (id, name, official_site_url)
VALUES ($1, $2, $3)
RETURNING id, name, official_site_url, created_at
`

type CreateArtistParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	OfficialSiteUrl string      `json:"official_site_url"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, arg.ID, arg.Name, arg.OfficialSiteUrl)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OfficialSiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :execrows
DELETE FROM artists WHERE id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, official_site_url, created_at FROM artists WHERE id = $1
`

func (q *Queries) GetArtist(ctx context.Context, id pgtype.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OfficialSiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getArtistByURL = `-- name: GetArtistByURL :one
SELECT id, name, official_site_url, created_at FROM artists WHERE official_site_url = $1
`

func (q *Queries) GetArtistByURL(ctx context.Context, officialSiteUrl string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByURL, officialSiteUrl)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OfficialSiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listAllArtists = `-- name: ListAllArtists :many
SELECT id, name, official_site_url, created_at FROM artists ORDER BY name
`

func (q *Queries) ListAllArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OfficialSiteUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, official_site_url, created_at FROM artists
WHERE ($3::text IS NULL OR name ILIKE '%' || $3 || '%')
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListArtistsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Query  *string `json:"query"`
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OfficialSiteUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists
SET name = $2, official_site_url = $3
WHERE id = $1
RETURNING id, name, official_site_url, created_at
`

type UpdateArtistParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	OfficialSiteUrl string      `json:"official_site_url"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist, arg.ID, arg.Name, arg.OfficialSiteUrl)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OfficialSiteUrl,
		&i.CreatedAt,
	)
	return i, err
}
