// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: concerts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConcerts = `-- name: CountConcerts :one
SELECT count(*)
FROM concerts c
WHERE ($1::uuid IS NULL OR c.artist_id = $1)
  AND ($2::date IS NULL OR c.date >= $2)
  AND ($3::date IS NULL OR c.date <= $3)
  AND ($4::boolean IS NULL OR c.is_festival = $4)
`

type CountConcertsParams struct {
	ArtistID   pgtype.UUID `json:"artist_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	IsFestival *bool       `json:"is_festival"`
}

func (q *Queries) CountConcerts(ctx context.Context, arg CountConcertsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConcerts,
		arg.ArtistID,
		arg.FromDate,
		arg.ToDate,
		arg.IsFestival,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDashboardConcerts = `-- name: CountDashboardConcerts :one
SELECT count(*)
FROM concerts c
JOIN user_artists ua ON ua.artist_id = c.artist_id
WHERE ua.user_id = $1 AND c.date >= CURRENT_DATE
`

func (q *Queries) CountDashboardConcerts(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDashboardConcerts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConcert = `-- name: CreateConcert :one
INSERT INTO concerts (
    id, artist_id, title, venue_name, venue_location, date,
    co_performers, is_festival, source_url, raw_text
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (artist_id, date, venue_name) DO NOTHING
RETURNING id, artist_id, title, venue_name, venue_location, date, co_performers, is_festival, source_url, raw_text, discovered_at, created_at
`

type CreateConcertParams struct {
	ID            pgtype.UUID `json:"id"`
	ArtistID      pgtype.UUID `json:"artist_id"`
	Title         string      `json:"title"`
	VenueName     string      `json:"venue_name"`
	VenueLocation string      `json:"venue_location"`
	Date          pgtype.Date `json:"date"`
	CoPerformers  []string    `json:"co_performers"`
	IsFestival    bool        `json:"is_festival"`
	SourceUrl     string      `json:"source_url"`
	RawText       string      `json:"raw_text"`
}

func (q *Queries) CreateConcert(ctx context.Context, arg CreateConcertParams) (Concert, error) {
	row := q.db.QueryRow(ctx, createConcert,
		arg.ID,
		arg.ArtistID,
		arg.Title,
		arg.VenueName,
		arg.VenueLocation,
		arg.Date,
		arg.CoPerformers,
		arg.IsFestival,
		arg.SourceUrl,
		arg.RawText,
	)
	var i Concert
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.VenueName,
		&i.VenueLocation,
		&i.Date,
		&i.CoPerformers,
		&i.IsFestival,
		&i.SourceUrl,
		&i.RawText,
		&i.DiscoveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConcert = `-- name: GetConcert :one
SELECT c.id, c.artist_id, c.title, c.venue_name, c.venue_location, c.date, c.co_performers, c.is_festival, c.source_url, c.raw_text, c.discovered_at, c.created_at, a.name AS artist_name
FROM concerts c
JOIN artists a ON a.id = c.artist_id
WHERE c.id = $1
`

type GetConcertRow struct {
	ID            pgtype.UUID        `json:"id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	Title         string             `json:"title"`
	VenueName     string             `json:"venue_name"`
	VenueLocation string             `json:"venue_location"`
	Date          pgtype.Date        `json:"date"`
	CoPerformers  []string           `json:"co_performers"`
	IsFestival    bool               `json:"is_festival"`
	SourceUrl     string             `json:"source_url"`
	RawText       string             `json:"raw_text"`
	DiscoveredAt  pgtype.Timestamptz `json:"discovered_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ArtistName    string             `json:"artist_name"`
}

func (q *Queries) GetConcert(ctx context.Context, id pgtype.UUID) (GetConcertRow, error) {
	row := q.db.QueryRow(ctx, getConcert, id)
	var i GetConcertRow
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.VenueName,
		&i.VenueLocation,
		&i.Date,
		&i.CoPerformers,
		&i.IsFestival,
		&i.SourceUrl,
		&i.RawText,
		&i.DiscoveredAt,
		&i.CreatedAt,
		&i.ArtistName,
	)
	return i, err
}

const listConcerts = `-- name: ListConcerts :many
SELECT c.id, c.artist_id, c.title, c.venue_name, c.venue_location, c.date, c.co_performers, c.is_festival, c.source_url, c.raw_text, c.discovered_at, c.created_at, a.name AS artist_name
FROM concerts c
JOIN artists a ON a.id = c.artist_id
WHERE ($3::uuid IS NULL OR c.artist_id = $3)
  AND ($4::date IS NULL OR c.date >= $4)
  AND ($5::date IS NULL OR c.date <= $5)
  AND ($6::boolean IS NULL OR c.is_festival = $6)
ORDER BY c.date ASC
LIMIT $1 OFFSET $2
`

type ListConcertsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	ArtistID   pgtype.UUID `json:"artist_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	IsFestival *bool       `json:"is_festival"`
}

type ListConcertsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	Title         string             `json:"title"`
	VenueName     string             `json:"venue_name"`
	VenueLocation string             `json:"venue_location"`
	Date          pgtype.Date        `json:"date"`
	CoPerformers  []string           `json:"co_performers"`
	IsFestival    bool               `json:"is_festival"`
	SourceUrl     string             `json:"source_url"`
	RawText       string             `json:"raw_text"`
	DiscoveredAt  pgtype.Timestamptz `json:"discovered_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ArtistName    string             `json:"artist_name"`
}

func (q *Queries) ListConcerts(ctx context.Context, arg ListConcertsParams) ([]ListConcertsRow, error) {
	rows, err := q.db.Query(ctx, listConcerts,
		arg.Limit,
		arg.Offset,
		arg.ArtistID,
		arg.FromDate,
		arg.ToDate,
		arg.IsFestival,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConcertsRow
	for rows.Next() {
		var i ListConcertsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.VenueName,
			&i.VenueLocation,
			&i.Date,
			&i.CoPerformers,
			&i.IsFestival,
			&i.SourceUrl,
			&i.RawText,
			&i.DiscoveredAt,
			&i.CreatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardConcerts = `-- name: ListDashboardConcerts :many
SELECT c.id, c.artist_id, c.title, c.venue_name, c.venue_location, c.date, c.co_performers, c.is_festival, c.source_url, c.raw_text, c.discovered_at, c.created_at, a.name AS artist_name
FROM concerts c
JOIN artists a ON a.id = c.artist_id
JOIN user_artists ua ON ua.artist_id = c.artist_id
WHERE ua.user_id = $1 AND c.date >= CURRENT_DATE
ORDER BY c.date ASC
LIMIT $2 OFFSET $3
`

type ListDashboardConcertsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListDashboardConcertsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	Title         string             `json:"title"`
	VenueName     string             `json:"venue_name"`
	VenueLocation string             `json:"venue_location"`
	Date          pgtype.Date        `json:"date"`
	CoPerformers  []string           `json:"co_performers"`
	IsFestival    bool               `json:"is_festival"`
	SourceUrl     string             `json:"source_url"`
	RawText       string             `json:"raw_text"`
	DiscoveredAt  pgtype.Timestamptz `json:"discovered_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ArtistName    string             `json:"artist_name"`
}

func (q *Queries) ListDashboardConcerts(ctx context.Context, arg ListDashboardConcertsParams) ([]ListDashboardConcertsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardConcerts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardConcertsRow
	for rows.Next() {
		var i ListDashboardConcertsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.VenueName,
			&i.VenueLocation,
			&i.Date,
			&i.CoPerformers,
			&i.IsFestival,
			&i.SourceUrl,
			&i.RawText,
			&i.DiscoveredAt,
			&i.CreatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
