// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followArtist = `-- name: FollowArtist :exec
INSERT INTO user_artists (user_id, artist_id)
VALUES ($1, $2)
`

type FollowArtistParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ArtistID pgtype.UUID `json:"artist_id"`
}

func (q *Queries) FollowArtist(ctx context.Context, arg FollowArtistParams) error {
	_, err := q.db.Exec(ctx, followArtist, arg.UserID, arg.ArtistID)
	return err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM user_artists WHERE user_id = $1 AND artist_id = $2
)
`

type IsFollowingParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ArtistID pgtype.UUID `json:"artist_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.UserID, arg.ArtistID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowedArtists = `-- name: ListFollowedArtists :many
SELECT a.id, a.name, a.official_site_url, a.created_at
FROM artists a
JOIN user_artists ua ON ua.artist_id = a.id
WHERE ua.user_id = $1
ORDER BY a.name
`

func (q *Queries) ListFollowedArtists(ctx context.Context, userID pgtype.UUID) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listFollowedArtists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OfficialSiteUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowArtist = `-- name: UnfollowArtist :execrows
DELETE FROM user_artists WHERE user_id = $1 AND artist_id = $2
`

type UnfollowArtistParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ArtistID pgtype.UUID `json:"artist_id"`
}

func (q *Queries) UnfollowArtist(ctx context.Context, arg UnfollowArtistParams) (int64, error) {
	result, err := q.db.Exec(ctx, unfollowArtist, arg.UserID, arg.ArtistID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
