// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	OfficialSiteUrl string             `json:"official_site_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Concert struct {
	ID            pgtype.UUID        `json:"id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	Title         string             `json:"title"`
	VenueName     string             `json:"venue_name"`
	VenueLocation string             `json:"venue_location"`
	Date          pgtype.Date        `json:"date"`
	CoPerformers  []string           `json:"co_performers"`
	IsFestival    bool               `json:"is_festival"`
	SourceUrl     string             `json:"source_url"`
	RawText       string             `json:"raw_text"`
	DiscoveredAt  pgtype.Timestamptz `json:"discovered_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ScrapeJob struct {
	ID           pgtype.UUID        `json:"id"`
	ArtistID     pgtype.UUID        `json:"artist_id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage *string            `json:"error_message"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserArtist struct {
	UserID     pgtype.UUID        `json:"user_id"`
	ArtistID   pgtype.UUID        `json:"artist_id"`
	FollowedAt pgtype.Timestamptz `json:"followed_at"`
}
