// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountArtists(ctx context.Context, query *string) (int64, error)
	CountConcerts(ctx context.Context, arg CountConcertsParams) (int64, error)
	CountDashboardConcerts(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountScrapeJobs(ctx context.Context, arg CountScrapeJobsParams) (int64, error)
	CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error)
	CreateConcert(ctx context.Context, arg CreateConcertParams) (Concert, error)
	CreateScrapeJob(ctx context.Context, arg CreateScrapeJobParams) (ScrapeJob, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArtist(ctx context.Context, id pgtype.UUID) (int64, error)
	FollowArtist(ctx context.Context, arg FollowArtistParams) error
	GetArtist(ctx context.Context, id pgtype.UUID) (Artist, error)
	GetArtistByURL(ctx context.Context, officialSiteUrl string) (Artist, error)
	GetConcert(ctx context.Context, id pgtype.UUID) (GetConcertRow, error)
	GetScrapeJob(ctx context.Context, id pgtype.UUID) (GetScrapeJobRow, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	ListAllArtists(ctx context.Context) ([]Artist, error)
	ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error)
	ListConcerts(ctx context.Context, arg ListConcertsParams) ([]ListConcertsRow, error)
	ListDashboardConcerts(ctx context.Context, arg ListDashboardConcertsParams) ([]ListDashboardConcertsRow, error)
	ListFollowedArtists(ctx context.Context, userID pgtype.UUID) ([]Artist, error)
	ListScrapeJobs(ctx context.Context, arg ListScrapeJobsParams) ([]ListScrapeJobsRow, error)
	UnfollowArtist(ctx context.Context, arg UnfollowArtistParams) (int64, error)
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error)
	UpdateScrapeJobStatus(ctx context.Context, arg UpdateScrapeJobStatusParams) (ScrapeJob, error)
}

var _ Querier = (*Queries)(nil)
