// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scrape_jobs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countScrapeJobs = `-- name: CountScrapeJobs :one
SELECT count(*)
FROM scrape_jobs sj
WHERE ($1::uuid IS NULL OR sj.artist_id = $1)
  AND ($2::text IS NULL OR sj.status = $2)
`

type CountScrapeJobsParams struct {
	ArtistID pgtype.UUID `json:"artist_id"`
	Status   *string     `json:"status"`
}

func (q *Queries) CountScrapeJobs(ctx context.Context, arg CountScrapeJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScrapeJobs, arg.ArtistID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScrapeJob = `-- name: CreateScrapeJob :one
INSERT INTO scrape_jobs (id, artist_id, status)
VALUES ($1, $2, $3)
RETURNING id, artist_id, status, started_at, finished_at, error_message
`

type CreateScrapeJobParams struct {
	ID       pgtype.UUID `json:"id"`
	ArtistID pgtype.UUID `json:"artist_id"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateScrapeJob(ctx context.Context, arg CreateScrapeJobParams) (ScrapeJob, error) {
	row := q.db.QueryRow(ctx, createScrapeJob, arg.ID, arg.ArtistID, arg.Status)
	var i ScrapeJob
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getScrapeJob = `-- name: GetScrapeJob :one
SELECT sj.id, sj.artist_id, sj.status, sj.started_at, sj.finished_at, sj.error_message, a.name AS artist_name
FROM scrape_jobs sj
JOIN artists a ON a.id = sj.artist_id
WHERE sj.id = $1
`

type GetScrapeJobRow struct {
	ID           pgtype.UUID        `json:"id"`
	ArtistID     pgtype.UUID        `json:"artist_id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage *string            `json:"error_message"`
	ArtistName   string             `json:"artist_name"`
}

func (q *Queries) GetScrapeJob(ctx context.Context, id pgtype.UUID) (GetScrapeJobRow, error) {
	row := q.db.QueryRow(ctx, getScrapeJob, id)
	var i GetScrapeJobRow
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.ArtistName,
	)
	return i, err
}

const listScrapeJobs = `-- name: ListScrapeJobs :many
SELECT sj.id, sj.artist_id, sj.status, sj.started_at, sj.finished_at, sj.error_message, a.name AS artist_name
FROM scrape_jobs sj
JOIN artists a ON a.id = sj.artist_id
WHERE ($3::uuid IS NULL OR sj.artist_id = $3)
  AND ($4::text IS NULL OR sj.status = $4)
ORDER BY sj.id
LIMIT $1 OFFSET $2
`

type ListScrapeJobsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	ArtistID pgtype.UUID `json:"artist_id"`
	Status   *string     `json:"status"`
}

type ListScrapeJobsRow struct {
	ID           pgtype.UUID        `json:"id"`
	ArtistID     pgtype.UUID        `json:"artist_id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage *string            `json:"error_message"`
	ArtistName   string             `json:"artist_name"`
}

func (q *Queries) ListScrapeJobs(ctx context.Context, arg ListScrapeJobsParams) ([]ListScrapeJobsRow, error) {
	rows, err := q.db.Query(ctx, listScrapeJobs,
		arg.Limit,
		arg.Offset,
		arg.ArtistID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScrapeJobsRow
	for rows.Next() {
		var i ListScrapeJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScrapeJobStatus = `-- name: UpdateScrapeJobStatus :one
UPDATE scrape_jobs
SET status = $2, started_at = $3, finished_at = $4, error_message = $5
WHERE id = $1
RETURNING id, artist_id, status, started_at, finished_at, error_message
`

type UpdateScrapeJobStatusParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage *string            `json:"error_message"`
}

func (q *Queries) UpdateScrapeJobStatus(ctx context.Context, arg UpdateScrapeJobStatusParams) (ScrapeJob, error) {
	row := q.db.QueryRow(ctx, updateScrapeJobStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorMessage,
	)
	var i ScrapeJob
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
	)
	return i, err
}
