// Package oas contains code generated by ogen from docs/api/openapi.yaml.
// Regenerate with `go generate ./...` after editing the spec.
package oas

//go:generate go tool ogen -target . -package oas -clean ../../../docs/api/openapi.yaml
