// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AdminScrapeJobsGet implements GET /admin/scrape-jobs operation.
//
// スクレイピングジョブ一覧.
//
// GET /admin/scrape-jobs
func (UnimplementedHandler) AdminScrapeJobsGet(ctx context.Context, params AdminScrapeJobsGetParams) (r *ScrapeJobList, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminScrapeJobsJobIdGet implements GET /admin/scrape-jobs/{jobId} operation.
//
// スクレイピングジョブ詳細.
//
// GET /admin/scrape-jobs/{jobId}
func (UnimplementedHandler) AdminScrapeJobsJobIdGet(ctx context.Context, params AdminScrapeJobsJobIdGetParams) (r AdminScrapeJobsJobIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminScrapePost implements POST /admin/scrape operation.
//
// 指定アーティスト（省略時は全件）のスクレイピングを即時トリガーする。.
//
// POST /admin/scrape
func (UnimplementedHandler) AdminScrapePost(ctx context.Context, req OptTriggerScrapeRequest) (r *TriggerScrapeResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ArtistsArtistIdDelete implements DELETE /artists/{artistId} operation.
//
// アーティスト削除（管理者）.
//
// DELETE /artists/{artistId}
func (UnimplementedHandler) ArtistsArtistIdDelete(ctx context.Context, params ArtistsArtistIdDeleteParams) (r ArtistsArtistIdDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArtistsArtistIdGet implements GET /artists/{artistId} operation.
//
// アーティスト取得.
//
// GET /artists/{artistId}
func (UnimplementedHandler) ArtistsArtistIdGet(ctx context.Context, params ArtistsArtistIdGetParams) (r ArtistsArtistIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArtistsArtistIdPut implements PUT /artists/{artistId} operation.
//
// アーティスト更新（管理者）.
//
// PUT /artists/{artistId}
func (UnimplementedHandler) ArtistsArtistIdPut(ctx context.Context, req *UpdateArtistRequest, params ArtistsArtistIdPutParams) (r ArtistsArtistIdPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArtistsGet implements GET /artists operation.
//
// アーティスト一覧取得.
//
// GET /artists
func (UnimplementedHandler) ArtistsGet(ctx context.Context, params ArtistsGetParams) (r *ArtistList, _ error) {
	return r, ht.ErrNotImplemented
}

// ArtistsPost implements POST /artists operation.
//
// アーティスト追加（管理者）.
//
// POST /artists
func (UnimplementedHandler) ArtistsPost(ctx context.Context, req *CreateArtistRequest) (r ArtistsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConcertsConcertIdGet implements GET /concerts/{concertId} operation.
//
// コンサート詳細取得.
//
// GET /concerts/{concertId}
func (UnimplementedHandler) ConcertsConcertIdGet(ctx context.Context, params ConcertsConcertIdGetParams) (r ConcertsConcertIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConcertsGet implements GET /concerts operation.
//
// コンサート一覧取得.
//
// GET /concerts
func (UnimplementedHandler) ConcertsGet(ctx context.Context, params ConcertsGetParams) (r *ConcertList, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// ユーザー登録.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context, req *CreateUserRequest) (r UsersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdDashboardGet implements GET /users/{userId}/dashboard operation.
//
// フォロー中アーティストの今後のライブ一覧を返す。 `is_new` が true
// のものは過去7日以内に discovered_at が設定されたライブ。.
//
// GET /users/{userId}/dashboard
func (UnimplementedHandler) UsersUserIdDashboardGet(ctx context.Context, params UsersUserIdDashboardGetParams) (r UsersUserIdDashboardGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdFollowsArtistIdDelete implements DELETE /users/{userId}/follows/{artistId} operation.
//
// アーティストのフォロー解除.
//
// DELETE /users/{userId}/follows/{artistId}
func (UnimplementedHandler) UsersUserIdFollowsArtistIdDelete(ctx context.Context, params UsersUserIdFollowsArtistIdDeleteParams) (r UsersUserIdFollowsArtistIdDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdFollowsGet implements GET /users/{userId}/follows operation.
//
// フォロー中アーティスト一覧.
//
// GET /users/{userId}/follows
func (UnimplementedHandler) UsersUserIdFollowsGet(ctx context.Context, params UsersUserIdFollowsGetParams) (r UsersUserIdFollowsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdFollowsPost implements POST /users/{userId}/follows operation.
//
// アーティストをフォロー.
//
// POST /users/{userId}/follows
func (UnimplementedHandler) UsersUserIdFollowsPost(ctx context.Context, req *FollowArtistRequest, params UsersUserIdFollowsPostParams) (r UsersUserIdFollowsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdGet implements GET /users/{userId} operation.
//
// ユーザー取得.
//
// GET /users/{userId}
func (UnimplementedHandler) UsersUserIdGet(ctx context.Context, params UsersUserIdGetParams) (r UsersUserIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
