// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/Artist
type Artist struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	OfficialSiteURL url.URL   `json:"official_site_url"`
	CreatedAt       time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Artist) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Artist) GetName() string {
	return s.Name
}

// GetOfficialSiteURL returns the value of OfficialSiteURL.
func (s *Artist) GetOfficialSiteURL() url.URL {
	return s.OfficialSiteURL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Artist) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Artist) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Artist) SetName(val string) {
	s.Name = val
}

// SetOfficialSiteURL sets the value of OfficialSiteURL.
func (s *Artist) SetOfficialSiteURL(val url.URL) {
	s.OfficialSiteURL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Artist) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*Artist) artistsArtistIdGetRes() {}
func (*Artist) artistsArtistIdPutRes() {}
func (*Artist) artistsPostRes()        {}

// Ref: #/components/schemas/ArtistList
type ArtistList struct {
	Items []Artist `json:"items"`
	Total int      `json:"total"`
}

// GetItems returns the value of Items.
func (s *ArtistList) GetItems() []Artist {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *ArtistList) GetTotal() int {
	return s.Total
}

// SetItems sets the value of Items.
func (s *ArtistList) SetItems(val []Artist) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *ArtistList) SetTotal(val int) {
	s.Total = val
}

func (*ArtistList) usersUserIdFollowsGetRes() {}

// ArtistsArtistIdDeleteNoContent is response for ArtistsArtistIdDelete operation.
type ArtistsArtistIdDeleteNoContent struct{}

func (*ArtistsArtistIdDeleteNoContent) artistsArtistIdDeleteRes() {}

type ArtistsArtistIdPutBadRequest ErrorResponse

func (*ArtistsArtistIdPutBadRequest) artistsArtistIdPutRes() {}

type ArtistsArtistIdPutNotFound ErrorResponse

func (*ArtistsArtistIdPutNotFound) artistsArtistIdPutRes() {}

type ArtistsPostBadRequest ErrorResponse

func (*ArtistsPostBadRequest) artistsPostRes() {}

type ArtistsPostConflict ErrorResponse

func (*ArtistsPostConflict) artistsPostRes() {}

// Ref: #/components/schemas/Concert
type Concert struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
	// JOIN済みのアーティスト名（表示用）.
	ArtistName    string    `json:"artist_name"`
	Title         OptString `json:"title"`
	VenueName     string    `json:"venue_name"`
	VenueLocation string    `json:"venue_location"`
	Date          time.Time `json:"date"`
	CoPerformers  []string  `json:"co_performers"`
	IsFestival    bool      `json:"is_festival"`
	SourceURL     url.URL   `json:"source_url"`
	DiscoveredAt  time.Time `json:"discovered_at"`
	CreatedAt     time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Concert) GetID() uuid.UUID {
	return s.ID
}

// GetArtistID returns the value of ArtistID.
func (s *Concert) GetArtistID() uuid.UUID {
	return s.ArtistID
}

// GetArtistName returns the value of ArtistName.
func (s *Concert) GetArtistName() string {
	return s.ArtistName
}

// GetTitle returns the value of Title.
func (s *Concert) GetTitle() OptString {
	return s.Title
}

// GetVenueName returns the value of VenueName.
func (s *Concert) GetVenueName() string {
	return s.VenueName
}

// GetVenueLocation returns the value of VenueLocation.
func (s *Concert) GetVenueLocation() string {
	return s.VenueLocation
}

// GetDate returns the value of Date.
func (s *Concert) GetDate() time.Time {
	return s.Date
}

// GetCoPerformers returns the value of CoPerformers.
func (s *Concert) GetCoPerformers() []string {
	return s.CoPerformers
}

// GetIsFestival returns the value of IsFestival.
func (s *Concert) GetIsFestival() bool {
	return s.IsFestival
}

// GetSourceURL returns the value of SourceURL.
func (s *Concert) GetSourceURL() url.URL {
	return s.SourceURL
}

// GetDiscoveredAt returns the value of DiscoveredAt.
func (s *Concert) GetDiscoveredAt() time.Time {
	return s.DiscoveredAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Concert) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Concert) SetID(val uuid.UUID) {
	s.ID = val
}

// SetArtistID sets the value of ArtistID.
func (s *Concert) SetArtistID(val uuid.UUID) {
	s.ArtistID = val
}

// SetArtistName sets the value of ArtistName.
func (s *Concert) SetArtistName(val string) {
	s.ArtistName = val
}

// SetTitle sets the value of Title.
func (s *Concert) SetTitle(val OptString) {
	s.Title = val
}

// SetVenueName sets the value of VenueName.
func (s *Concert) SetVenueName(val string) {
	s.VenueName = val
}

// SetVenueLocation sets the value of VenueLocation.
func (s *Concert) SetVenueLocation(val string) {
	s.VenueLocation = val
}

// SetDate sets the value of Date.
func (s *Concert) SetDate(val time.Time) {
	s.Date = val
}

// SetCoPerformers sets the value of CoPerformers.
func (s *Concert) SetCoPerformers(val []string) {
	s.CoPerformers = val
}

// SetIsFestival sets the value of IsFestival.
func (s *Concert) SetIsFestival(val bool) {
	s.IsFestival = val
}

// SetSourceURL sets the value of SourceURL.
func (s *Concert) SetSourceURL(val url.URL) {
	s.SourceURL = val
}

// SetDiscoveredAt sets the value of DiscoveredAt.
func (s *Concert) SetDiscoveredAt(val time.Time) {
	s.DiscoveredAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Concert) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*Concert) concertsConcertIdGetRes() {}

// Ref: #/components/schemas/ConcertList
type ConcertList struct {
	Items []Concert `json:"items"`
	Total int       `json:"total"`
}

// GetItems returns the value of Items.
func (s *ConcertList) GetItems() []Concert {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *ConcertList) GetTotal() int {
	return s.Total
}

// SetItems sets the value of Items.
func (s *ConcertList) SetItems(val []Concert) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *ConcertList) SetTotal(val int) {
	s.Total = val
}

// Ref: #/components/schemas/CreateArtistRequest
type CreateArtistRequest struct {
	Name            string  `json:"name"`
	OfficialSiteURL url.URL `json:"official_site_url"`
}

// GetName returns the value of Name.
func (s *CreateArtistRequest) GetName() string {
	return s.Name
}

// GetOfficialSiteURL returns the value of OfficialSiteURL.
func (s *CreateArtistRequest) GetOfficialSiteURL() url.URL {
	return s.OfficialSiteURL
}

// SetName sets the value of Name.
func (s *CreateArtistRequest) SetName(val string) {
	s.Name = val
}

// SetOfficialSiteURL sets the value of OfficialSiteURL.
func (s *CreateArtistRequest) SetOfficialSiteURL(val url.URL) {
	s.OfficialSiteURL = val
}

// Ref: #/components/schemas/CreateUserRequest
type CreateUserRequest struct {
	Email string `json:"email"`
}

// GetEmail returns the value of Email.
func (s *CreateUserRequest) GetEmail() string {
	return s.Email
}

// SetEmail sets the value of Email.
func (s *CreateUserRequest) SetEmail(val string) {
	s.Email = val
}

// Merged schema.
// Ref: #/components/schemas/DashboardConcert
type DashboardConcert struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
	// JOIN済みのアーティスト名（表示用）.
	ArtistName    string    `json:"artist_name"`
	Title         OptString `json:"title"`
	VenueName     string    `json:"venue_name"`
	VenueLocation string    `json:"venue_location"`
	Date          time.Time `json:"date"`
	CoPerformers  []string  `json:"co_performers"`
	IsFestival    bool      `json:"is_festival"`
	SourceURL     url.URL   `json:"source_url"`
	DiscoveredAt  time.Time `json:"discovered_at"`
	CreatedAt     time.Time `json:"created_at"`
	// 過去7日以内に発見されたライブの場合 true.
	IsNew bool `json:"is_new"`
}

// GetID returns the value of ID.
func (s *DashboardConcert) GetID() uuid.UUID {
	return s.ID
}

// GetArtistID returns the value of ArtistID.
func (s *DashboardConcert) GetArtistID() uuid.UUID {
	return s.ArtistID
}

// GetArtistName returns the value of ArtistName.
func (s *DashboardConcert) GetArtistName() string {
	return s.ArtistName
}

// GetTitle returns the value of Title.
func (s *DashboardConcert) GetTitle() OptString {
	return s.Title
}

// GetVenueName returns the value of VenueName.
func (s *DashboardConcert) GetVenueName() string {
	return s.VenueName
}

// GetVenueLocation returns the value of VenueLocation.
func (s *DashboardConcert) GetVenueLocation() string {
	return s.VenueLocation
}

// GetDate returns the value of Date.
func (s *DashboardConcert) GetDate() time.Time {
	return s.Date
}

// GetCoPerformers returns the value of CoPerformers.
func (s *DashboardConcert) GetCoPerformers() []string {
	return s.CoPerformers
}

// GetIsFestival returns the value of IsFestival.
func (s *DashboardConcert) GetIsFestival() bool {
	return s.IsFestival
}

// GetSourceURL returns the value of SourceURL.
func (s *DashboardConcert) GetSourceURL() url.URL {
	return s.SourceURL
}

// GetDiscoveredAt returns the value of DiscoveredAt.
func (s *DashboardConcert) GetDiscoveredAt() time.Time {
	return s.DiscoveredAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *DashboardConcert) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetIsNew returns the value of IsNew.
func (s *DashboardConcert) GetIsNew() bool {
	return s.IsNew
}

// SetID sets the value of ID.
func (s *DashboardConcert) SetID(val uuid.UUID) {
	s.ID = val
}

// SetArtistID sets the value of ArtistID.
func (s *DashboardConcert) SetArtistID(val uuid.UUID) {
	s.ArtistID = val
}

// SetArtistName sets the value of ArtistName.
func (s *DashboardConcert) SetArtistName(val string) {
	s.ArtistName = val
}

// SetTitle sets the value of Title.
func (s *DashboardConcert) SetTitle(val OptString) {
	s.Title = val
}

// SetVenueName sets the value of VenueName.
func (s *DashboardConcert) SetVenueName(val string) {
	s.VenueName = val
}

// SetVenueLocation sets the value of VenueLocation.
func (s *DashboardConcert) SetVenueLocation(val string) {
	s.VenueLocation = val
}

// SetDate sets the value of Date.
func (s *DashboardConcert) SetDate(val time.Time) {
	s.Date = val
}

// SetCoPerformers sets the value of CoPerformers.
func (s *DashboardConcert) SetCoPerformers(val []string) {
	s.CoPerformers = val
}

// SetIsFestival sets the value of IsFestival.
func (s *DashboardConcert) SetIsFestival(val bool) {
	s.IsFestival = val
}

// SetSourceURL sets the value of SourceURL.
func (s *DashboardConcert) SetSourceURL(val url.URL) {
	s.SourceURL = val
}

// SetDiscoveredAt sets the value of DiscoveredAt.
func (s *DashboardConcert) SetDiscoveredAt(val time.Time) {
	s.DiscoveredAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *DashboardConcert) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetIsNew sets the value of IsNew.
func (s *DashboardConcert) SetIsNew(val bool) {
	s.IsNew = val
}

// Ref: #/components/schemas/DashboardResponse
type DashboardResponse struct {
	Items []DashboardConcert `json:"items"`
	Total int                `json:"total"`
}

// GetItems returns the value of Items.
func (s *DashboardResponse) GetItems() []DashboardConcert {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *DashboardResponse) GetTotal() int {
	return s.Total
}

// SetItems sets the value of Items.
func (s *DashboardResponse) SetItems(val []DashboardConcert) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *DashboardResponse) SetTotal(val int) {
	s.Total = val
}

func (*DashboardResponse) usersUserIdDashboardGetRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) adminScrapeJobsJobIdGetRes()          {}
func (*ErrorResponse) artistsArtistIdDeleteRes()            {}
func (*ErrorResponse) artistsArtistIdGetRes()               {}
func (*ErrorResponse) concertsConcertIdGetRes()             {}
func (*ErrorResponse) usersUserIdDashboardGetRes()          {}
func (*ErrorResponse) usersUserIdFollowsArtistIdDeleteRes() {}
func (*ErrorResponse) usersUserIdFollowsGetRes()            {}
func (*ErrorResponse) usersUserIdGetRes()                   {}

// Ref: #/components/schemas/FollowArtistRequest
type FollowArtistRequest struct {
	ArtistID uuid.UUID `json:"artist_id"`
}

// GetArtistID returns the value of ArtistID.
func (s *FollowArtistRequest) GetArtistID() uuid.UUID {
	return s.ArtistID
}

// SetArtistID sets the value of ArtistID.
func (s *FollowArtistRequest) SetArtistID(val uuid.UUID) {
	s.ArtistID = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilDateTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptScrapeJobStatus returns new OptScrapeJobStatus with value set to v.
func NewOptScrapeJobStatus(v ScrapeJobStatus) OptScrapeJobStatus {
	return OptScrapeJobStatus{
		Value: v,
		Set:   true,
	}
}

// OptScrapeJobStatus is optional ScrapeJobStatus.
type OptScrapeJobStatus struct {
	Value ScrapeJobStatus
	Set   bool
}

// IsSet returns true if OptScrapeJobStatus was set.
func (o OptScrapeJobStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptScrapeJobStatus) Reset() {
	var v ScrapeJobStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptScrapeJobStatus) SetTo(v ScrapeJobStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptScrapeJobStatus) Get() (v ScrapeJobStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptScrapeJobStatus) Or(d ScrapeJobStatus) ScrapeJobStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTriggerScrapeRequest returns new OptTriggerScrapeRequest with value set to v.
func NewOptTriggerScrapeRequest(v TriggerScrapeRequest) OptTriggerScrapeRequest {
	return OptTriggerScrapeRequest{
		Value: v,
		Set:   true,
	}
}

// OptTriggerScrapeRequest is optional TriggerScrapeRequest.
type OptTriggerScrapeRequest struct {
	Value TriggerScrapeRequest
	Set   bool
}

// IsSet returns true if OptTriggerScrapeRequest was set.
func (o OptTriggerScrapeRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTriggerScrapeRequest) Reset() {
	var v TriggerScrapeRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTriggerScrapeRequest) SetTo(v TriggerScrapeRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTriggerScrapeRequest) Get() (v TriggerScrapeRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTriggerScrapeRequest) Or(d TriggerScrapeRequest) TriggerScrapeRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ScrapeJob
type ScrapeJob struct {
	ID           uuid.UUID       `json:"id"`
	ArtistID     uuid.UUID       `json:"artist_id"`
	ArtistName   string          `json:"artist_name"`
	Status       ScrapeJobStatus `json:"status"`
	StartedAt    OptNilDateTime  `json:"started_at"`
	FinishedAt   OptNilDateTime  `json:"finished_at"`
	ErrorMessage OptNilString    `json:"error_message"`
}

// GetID returns the value of ID.
func (s *ScrapeJob) GetID() uuid.UUID {
	return s.ID
}

// GetArtistID returns the value of ArtistID.
func (s *ScrapeJob) GetArtistID() uuid.UUID {
	return s.ArtistID
}

// GetArtistName returns the value of ArtistName.
func (s *ScrapeJob) GetArtistName() string {
	return s.ArtistName
}

// GetStatus returns the value of Status.
func (s *ScrapeJob) GetStatus() ScrapeJobStatus {
	return s.Status
}

// GetStartedAt returns the value of StartedAt.
func (s *ScrapeJob) GetStartedAt() OptNilDateTime {
	return s.StartedAt
}

// GetFinishedAt returns the value of FinishedAt.
func (s *ScrapeJob) GetFinishedAt() OptNilDateTime {
	return s.FinishedAt
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *ScrapeJob) GetErrorMessage() OptNilString {
	return s.ErrorMessage
}

// SetID sets the value of ID.
func (s *ScrapeJob) SetID(val uuid.UUID) {
	s.ID = val
}

// SetArtistID sets the value of ArtistID.
func (s *ScrapeJob) SetArtistID(val uuid.UUID) {
	s.ArtistID = val
}

// SetArtistName sets the value of ArtistName.
func (s *ScrapeJob) SetArtistName(val string) {
	s.ArtistName = val
}

// SetStatus sets the value of Status.
func (s *ScrapeJob) SetStatus(val ScrapeJobStatus) {
	s.Status = val
}

// SetStartedAt sets the value of StartedAt.
func (s *ScrapeJob) SetStartedAt(val OptNilDateTime) {
	s.StartedAt = val
}

// SetFinishedAt sets the value of FinishedAt.
func (s *ScrapeJob) SetFinishedAt(val OptNilDateTime) {
	s.FinishedAt = val
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *ScrapeJob) SetErrorMessage(val OptNilString) {
	s.ErrorMessage = val
}

func (*ScrapeJob) adminScrapeJobsJobIdGetRes() {}

// Ref: #/components/schemas/ScrapeJobList
type ScrapeJobList struct {
	Items []ScrapeJob `json:"items"`
	Total int         `json:"total"`
}

// GetItems returns the value of Items.
func (s *ScrapeJobList) GetItems() []ScrapeJob {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *ScrapeJobList) GetTotal() int {
	return s.Total
}

// SetItems sets the value of Items.
func (s *ScrapeJobList) SetItems(val []ScrapeJob) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *ScrapeJobList) SetTotal(val int) {
	s.Total = val
}

// Ref: #/components/schemas/ScrapeJobStatus
type ScrapeJobStatus string

const (
	ScrapeJobStatusPending   ScrapeJobStatus = "pending"
	ScrapeJobStatusRunning   ScrapeJobStatus = "running"
	ScrapeJobStatusSucceeded ScrapeJobStatus = "succeeded"
	ScrapeJobStatusFailed    ScrapeJobStatus = "failed"
)

// AllValues returns all ScrapeJobStatus values.
func (ScrapeJobStatus) AllValues() []ScrapeJobStatus {
	return []ScrapeJobStatus{
		ScrapeJobStatusPending,
		ScrapeJobStatusRunning,
		ScrapeJobStatusSucceeded,
		ScrapeJobStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ScrapeJobStatus) MarshalText() ([]byte, error) {
	switch s {
	case ScrapeJobStatusPending:
		return []byte(s), nil
	case ScrapeJobStatusRunning:
		return []byte(s), nil
	case ScrapeJobStatusSucceeded:
		return []byte(s), nil
	case ScrapeJobStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ScrapeJobStatus) UnmarshalText(data []byte) error {
	switch ScrapeJobStatus(data) {
	case ScrapeJobStatusPending:
		*s = ScrapeJobStatusPending
		return nil
	case ScrapeJobStatusRunning:
		*s = ScrapeJobStatusRunning
		return nil
	case ScrapeJobStatusSucceeded:
		*s = ScrapeJobStatusSucceeded
		return nil
	case ScrapeJobStatusFailed:
		*s = ScrapeJobStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// 省略時は全アーティストを対象とする.
// Ref: #/components/schemas/TriggerScrapeRequest
type TriggerScrapeRequest struct {
	ArtistIds []uuid.UUID `json:"artist_ids"`
}

// GetArtistIds returns the value of ArtistIds.
func (s *TriggerScrapeRequest) GetArtistIds() []uuid.UUID {
	return s.ArtistIds
}

// SetArtistIds sets the value of ArtistIds.
func (s *TriggerScrapeRequest) SetArtistIds(val []uuid.UUID) {
	s.ArtistIds = val
}

// Ref: #/components/schemas/TriggerScrapeResponse
type TriggerScrapeResponse struct {
	// 作成されたジョブのID一覧.
	JobIds []uuid.UUID `json:"job_ids"`
}

// GetJobIds returns the value of JobIds.
func (s *TriggerScrapeResponse) GetJobIds() []uuid.UUID {
	return s.JobIds
}

// SetJobIds sets the value of JobIds.
func (s *TriggerScrapeResponse) SetJobIds(val []uuid.UUID) {
	s.JobIds = val
}

// Ref: #/components/schemas/UpdateArtistRequest
type UpdateArtistRequest struct {
	Name            OptString `json:"name"`
	OfficialSiteURL OptURI    `json:"official_site_url"`
}

// GetName returns the value of Name.
func (s *UpdateArtistRequest) GetName() OptString {
	return s.Name
}

// GetOfficialSiteURL returns the value of OfficialSiteURL.
func (s *UpdateArtistRequest) GetOfficialSiteURL() OptURI {
	return s.OfficialSiteURL
}

// SetName sets the value of Name.
func (s *UpdateArtistRequest) SetName(val OptString) {
	s.Name = val
}

// SetOfficialSiteURL sets the value of OfficialSiteURL.
func (s *UpdateArtistRequest) SetOfficialSiteURL(val OptURI) {
	s.OfficialSiteURL = val
}

// Ref: #/components/schemas/User
type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*User) usersPostRes()      {}
func (*User) usersUserIdGetRes() {}

type UsersPostBadRequest ErrorResponse

func (*UsersPostBadRequest) usersPostRes() {}

type UsersPostConflict ErrorResponse

func (*UsersPostConflict) usersPostRes() {}

// UsersUserIdFollowsArtistIdDeleteNoContent is response for UsersUserIdFollowsArtistIdDelete operation.
type UsersUserIdFollowsArtistIdDeleteNoContent struct{}

func (*UsersUserIdFollowsArtistIdDeleteNoContent) usersUserIdFollowsArtistIdDeleteRes() {}

type UsersUserIdFollowsPostConflict ErrorResponse

func (*UsersUserIdFollowsPostConflict) usersUserIdFollowsPostRes() {}

// UsersUserIdFollowsPostCreated is response for UsersUserIdFollowsPost operation.
type UsersUserIdFollowsPostCreated struct{}

func (*UsersUserIdFollowsPostCreated) usersUserIdFollowsPostRes() {}

type UsersUserIdFollowsPostNotFound ErrorResponse

func (*UsersUserIdFollowsPostNotFound) usersUserIdFollowsPostRes() {}
