// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AdminScrapeJobsGet implements GET /admin/scrape-jobs operation.
	//
	// スクレイピングジョブ一覧.
	//
	// GET /admin/scrape-jobs
	AdminScrapeJobsGet(ctx context.Context, params AdminScrapeJobsGetParams) (*ScrapeJobList, error)
	// AdminScrapeJobsJobIdGet implements GET /admin/scrape-jobs/{jobId} operation.
	//
	// スクレイピングジョブ詳細.
	//
	// GET /admin/scrape-jobs/{jobId}
	AdminScrapeJobsJobIdGet(ctx context.Context, params AdminScrapeJobsJobIdGetParams) (AdminScrapeJobsJobIdGetRes, error)
	// AdminScrapePost implements POST /admin/scrape operation.
	//
	// 指定アーティスト（省略時は全件）のスクレイピングを即時トリガーする。.
	//
	// POST /admin/scrape
	AdminScrapePost(ctx context.Context, req OptTriggerScrapeRequest) (*TriggerScrapeResponse, error)
	// ArtistsArtistIdDelete implements DELETE /artists/{artistId} operation.
	//
	// アーティスト削除（管理者）.
	//
	// DELETE /artists/{artistId}
	ArtistsArtistIdDelete(ctx context.Context, params ArtistsArtistIdDeleteParams) (ArtistsArtistIdDeleteRes, error)
	// ArtistsArtistIdGet implements GET /artists/{artistId} operation.
	//
	// アーティスト取得.
	//
	// GET /artists/{artistId}
	ArtistsArtistIdGet(ctx context.Context, params ArtistsArtistIdGetParams) (ArtistsArtistIdGetRes, error)
	// ArtistsArtistIdPut implements PUT /artists/{artistId} operation.
	//
	// アーティスト更新（管理者）.
	//
	// PUT /artists/{artistId}
	ArtistsArtistIdPut(ctx context.Context, req *UpdateArtistRequest, params ArtistsArtistIdPutParams) (ArtistsArtistIdPutRes, error)
	// ArtistsGet implements GET /artists operation.
	//
	// アーティスト一覧取得.
	//
	// GET /artists
	ArtistsGet(ctx context.Context, params ArtistsGetParams) (*ArtistList, error)
	// ArtistsPost implements POST /artists operation.
	//
	// アーティスト追加（管理者）.
	//
	// POST /artists
	ArtistsPost(ctx context.Context, req *CreateArtistRequest) (ArtistsPostRes, error)
	// ConcertsConcertIdGet implements GET /concerts/{concertId} operation.
	//
	// コンサート詳細取得.
	//
	// GET /concerts/{concertId}
	ConcertsConcertIdGet(ctx context.Context, params ConcertsConcertIdGetParams) (ConcertsConcertIdGetRes, error)
	// ConcertsGet implements GET /concerts operation.
	//
	// コンサート一覧取得.
	//
	// GET /concerts
	ConcertsGet(ctx context.Context, params ConcertsGetParams) (*ConcertList, error)
	// UsersPost implements POST /users operation.
	//
	// ユーザー登録.
	//
	// POST /users
	UsersPost(ctx context.Context, req *CreateUserRequest) (UsersPostRes, error)
	// UsersUserIdDashboardGet implements GET /users/{userId}/dashboard operation.
	//
	// フォロー中アーティストの今後のライブ一覧を返す。 `is_new` が true
	// のものは過去7日以内に discovered_at が設定されたライブ。.
	//
	// GET /users/{userId}/dashboard
	UsersUserIdDashboardGet(ctx context.Context, params UsersUserIdDashboardGetParams) (UsersUserIdDashboardGetRes, error)
	// UsersUserIdFollowsArtistIdDelete implements DELETE /users/{userId}/follows/{artistId} operation.
	//
	// アーティストのフォロー解除.
	//
	// DELETE /users/{userId}/follows/{artistId}
	UsersUserIdFollowsArtistIdDelete(ctx context.Context, params UsersUserIdFollowsArtistIdDeleteParams) (UsersUserIdFollowsArtistIdDeleteRes, error)
	// UsersUserIdFollowsGet implements GET /users/{userId}/follows operation.
	//
	// フォロー中アーティスト一覧.
	//
	// GET /users/{userId}/follows
	UsersUserIdFollowsGet(ctx context.Context, params UsersUserIdFollowsGetParams) (UsersUserIdFollowsGetRes, error)
	// UsersUserIdFollowsPost implements POST /users/{userId}/follows operation.
	//
	// アーティストをフォロー.
	//
	// POST /users/{userId}/follows
	UsersUserIdFollowsPost(ctx context.Context, req *FollowArtistRequest, params UsersUserIdFollowsPostParams) (UsersUserIdFollowsPostRes, error)
	// UsersUserIdGet implements GET /users/{userId} operation.
	//
	// ユーザー取得.
	//
	// GET /users/{userId}
	UsersUserIdGet(ctx context.Context, params UsersUserIdGetParams) (UsersUserIdGetRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
