// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AdminScrapeJobsGetOperation               OperationName = "AdminScrapeJobsGet"
	AdminScrapeJobsJobIdGetOperation          OperationName = "AdminScrapeJobsJobIdGet"
	AdminScrapePostOperation                  OperationName = "AdminScrapePost"
	ArtistsArtistIdDeleteOperation            OperationName = "ArtistsArtistIdDelete"
	ArtistsArtistIdGetOperation               OperationName = "ArtistsArtistIdGet"
	ArtistsArtistIdPutOperation               OperationName = "ArtistsArtistIdPut"
	ArtistsGetOperation                       OperationName = "ArtistsGet"
	ArtistsPostOperation                      OperationName = "ArtistsPost"
	ConcertsConcertIdGetOperation             OperationName = "ConcertsConcertIdGet"
	ConcertsGetOperation                      OperationName = "ConcertsGet"
	UsersPostOperation                        OperationName = "UsersPost"
	UsersUserIdDashboardGetOperation          OperationName = "UsersUserIdDashboardGet"
	UsersUserIdFollowsArtistIdDeleteOperation OperationName = "UsersUserIdFollowsArtistIdDelete"
	UsersUserIdFollowsGetOperation            OperationName = "UsersUserIdFollowsGet"
	UsersUserIdFollowsPostOperation           OperationName = "UsersUserIdFollowsPost"
	UsersUserIdGetOperation                   OperationName = "UsersUserIdGet"
)
