// Code generated by ogen, DO NOT EDIT.
package oas

type AdminScrapeJobsJobIdGetRes interface {
	adminScrapeJobsJobIdGetRes()
}

type ArtistsArtistIdDeleteRes interface {
	artistsArtistIdDeleteRes()
}

type ArtistsArtistIdGetRes interface {
	artistsArtistIdGetRes()
}

type ArtistsArtistIdPutRes interface {
	artistsArtistIdPutRes()
}

type ArtistsPostRes interface {
	artistsPostRes()
}

type ConcertsConcertIdGetRes interface {
	concertsConcertIdGetRes()
}

type UsersPostRes interface {
	usersPostRes()
}

type UsersUserIdDashboardGetRes interface {
	usersUserIdDashboardGetRes()
}

type UsersUserIdFollowsArtistIdDeleteRes interface {
	usersUserIdFollowsArtistIdDeleteRes()
}

type UsersUserIdFollowsGetRes interface {
	usersUserIdFollowsGetRes()
}

type UsersUserIdFollowsPostRes interface {
	usersUserIdFollowsPostRes()
}

type UsersUserIdGetRes interface {
	usersUserIdGetRes()
}
